### ISSUE TITLE
和原文的结果对比

### ISSUE THREAD

**Issue by rayLemond** [weixu000/DSH-pytorch#4]
12bits的cifar10，map跑出来是59+，原文61+。不确定是哪里的问题，想问问作者有没有复现一下paper里的性能？

**Comment by swuxyj** [comment]
我跑出来72，好得有点多，也没找到是哪的问题

**Comment by rayLemond** [comment]
又跑了一次，最高能到66，平均64上下。跟你跑出来的好像差得有点远？囧，跟github里这份代码有什么改动吗？网络结构？alpha或m？
